### PR TITLE
Add arch linux installation instructions

### PR DESCRIPTION
**Pull request by jonian**
I have created and will maintain an AUR package for Arch Linux. You can find it at https://aur.archlinux.org/packages/frum-bin.

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
@jonian 
Thank you for your contribution!

Ideally, the package base should be just frum and you should be able to install frum with the following command.

```
$ yay -S frum
```

Would it be possible for you to rename package base to just `frum`?

**Comment by jonian** [comment]
Packages in AUR must follow the naming below:

- frum : builds from source, tagged release
- frum-bin : pre-built binary, tagged release
- frum-git : builds from source, development branch

I will also add `frum` and `frum-git` in AUR and update the PR. All three packages can be available for the user to choose.  
I generaly prefer pre-built binaries because they install faster, that is why I created only frum-bin.

**Comment by TaKO8Ki** [comment]
@jonian 
Thank you for the information! Where do you find a package base rule? i'm curious about that.

**Comment by jonian** [comment]
Package base rules are available at https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Rules_of_submission. These rules apply only to AUR packages and not packages in the official repositories.

I will create the other packages later, today.

**Review by TaKO8Ki — APPROVED** [review]
Thanks!

**Pull request merged**
