### PR TITLE
Apply clippy lints

### PR DESCRIPTION
**Pull request by Br1ght0ne**
Applied Clippy lints with `cargo clippy --fix` and manually refactored some to make Clippy report 0 warnings :)

Notes:

- will every supported shell have completions? if not, changing signature of `customize_completions` might've been a bad move.

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
Thank you for your contribution!

> will every supported shell have completions? if not, changing signature of customize_completions might've been a bad move.

Yes. frum support bash, zsh and fish now. And I'm planning to support fish shell completion.

**Comment by TaKO8Ki** [comment]
@Br1ght0ne 
Is this PR still work-in-progress?

**Review by TaKO8Ki — APPROVED** [review]
Thank you!

**Comment by Br1ght0ne** [comment]
@TaKO8Ki Forgot to mark as ready. Thank you!

**Pull request merged**
