### PR TITLE
Use openssl@1.1 in Homebrew

### PR DESCRIPTION
**Pull request by TaKO8Ki**
changelog: Use openssl@1.1 in Homebrew

### CODE REVIEW

**Comment by robcresswell** [comment]
@TaKO8Ki Is this live in homebrew? I'm seeing openssl errors

**Comment by TaKO8Ki** [comment]
@robcresswell Could you try the following command? The latest version in Homebrew has a bug and you can understand what it is in https://github.com/TaKO8Ki/frum/issues/107. I will release v0.1.2 as soon as possible.

```
$ frum install [your version] --with-openssl-dir=$(brew --prefix openssl@1.1)
```

**Comment by robcresswell** [comment]
@TaKO8Ki That seems to work, thanks! No stress on releasing, I appreciate the work and the help!

**Comment by TaKO8Ki** [comment]
@robcresswell I'm happy that it worked!

**Pull request merged**
